use_wandb: False
use_sweep: False
seed: 0
gpus: 1
cpus: 1
num_sampels: 5
data_dir: '~/data'
dataset: 'prism_grid_dataset_224.hdf5'
batch_size: 1
val_batch_size: 1
recovery_interval: 0
checkpoint_path: './ckpt/'
check_val_every_n_epoch: 5
checkpoint_hist: 1
workers: 1
pin_mem: False
experiment: "koopman_GPT2_0_search"
project: "v1"
notes: "Staic field"

autoregressive: 
  name: "GPT2" 
  pretrained: False

embedding:
  name: 'koopman'
  pretrained: False
  tune: 
    backbone: ['conv', 'attention']
     

opt:
  name: 'adamw'
  eps: 1e-8
  momentum: 0.9
  beta0: 0.9
  beta1: 0.999
  weight_decay: 0.05
  clip_grad: null
  clip_mode: 'norm'

lr:
  sched: 'cosine'
  lr: 1e-3
  noise: null
  noise_pct: 0.67
  noise_std: 1.0
  cycle_mul: 1.0
  cycle_decay: 0.5
  cycle_limit: 1
  k_decay: 1.0
  warmup_lr: 1e-6
  min_lr: 1e-6
  epochs: 100
  epoch_repeats: 0
  start_epoch: null
  decay_epochs: 50
  warmup_epochs: 5
  cooldown_epochs: 25
  patience_epochs: 10
  decay_rate: 0.1
  multistep_milestones: [25, 50, 75, 100]