use_wandb: False
use_sweep: False
train_embed: False

seed: 0
gpus: 1
cpus: 1
workers: 4
pin_mem: False

batch_size: 1
val_batch_size: 1
recovery_interval: 0

data_dir: '~/data'
dataset: 'prism_grid_dataset_224.hdf5'

checkpoint_path: './ckpt/'
check_val_every_n_epoch: 2

experiment: "koopman_Backbone_search_0"
project: "v1"
notes: "Staic field"

embedding:
  name: 'koopman'
  pretrained: False
  ckpt_path: ""

  image_dim: 32
  channels: 3
  backbone: "TwinsSTV"
  fc_dim: 128
  embedding_dim: 128
  backbone_dim: 128

autoregressive: 
  name: "GPT2" 
  pretrained: False
  ckpt_path: ""

opt:
  name: 'adamw'
  eps: 1e-8
  momentum: 0.9
  beta0: 0.9
  beta1: 0.999
  weight_decay: 0.05

learning:
  sched: 'cosine'
  learning_rate: 1e-3
  k_decay: 1.0
  warmup_lr: 1e-6
  min_lr: 1e-6
  epochs: 100
  multistep_milestones: [25, 50, 75, 100]