# general
[META]
model_name: MicroMagnetism
n_embd: 128

exp_dir: ./log/magtense_micro_test/
checkpoint_dir: ./checkpoints/magtense_micro_test/test_config/
h5_file_train: ./magtense_micro_test/cube36_3d.h5
h5_file_eval: ./magtense_micro_test/cube36_3d.h5

device: cuda


[TRANSFORMER]
n_ctx: 16
n_layer: 6
n_head: 4
state_dims: [3, 36, 36]
activation_function: gelu_new
initializer_range: 0.05

embed_model_path: ./checkpoints/magtense_micro_test/test_config/embedding_model300.pth
viz_coords_path: magtense_micro_test\cube36_3d_coord.npy

plot_dir: ./plots/magtense_micro_test/config_ver/
plot_max: 500

overwrite_cached_data: Yes

ndata_train: -1
batch_size_train: 4
block_size_train: 16
stride_train: 6

ndata_eval: -1
batch_size_eval: 16
block_size_eval: 100
stride_eval: 100

use_viz: No

epochs: 300
lr: 1e-3
seed: 2
epoch_start: 0
save_steps: 50


[EMBED]
ndata_train: -1
batch_size_train: 64
block_size_train: 4
stride_train: 4

ndata_eval: 6
batch_size_eval: 16
block_size_eval: 32

epochs: 300
lr: 1e-3
seed: 2
epoch_start: 0
save_steps: 50


[EVAL]
init_embeds: 1
transformer_model_path: ./checkpoints/magtense_micro_test/test_config/transformer_MicroMagnetism250.pth
data: ./magtense_micro_test/cube36_3d.h5



use_wandb: False
seed: 0
gpus: 1
cpus: 1
num_sampels: 5
data_dir: '~/data'
dataset: 'prism_grid_dataset_224.hdf5'
batch_size: 1
val_batch_size: 1
recovery_interval: 0
checkpoint_path: './ckpt/'
check_val_every_n_epoch: 5
checkpoint_hist: 1
workers: 1
pin_mem: False
experiment: "koopman_GPT2_0_search"
project: "v1"
notes: "Staic field"

autoregressive: 
  name: "GPT2" 
  pretrained: False

embedding:
  name: 'koopman'
  pretrained: False
  tune: 
    backbone: ['conv', 'attention']
     

opt:
  name: 'adamw'
  eps: 1e-8
  momentum: 0.9
  beta0: 0.9
  beta1: 0.999
  weight_decay: 0.05
  clip_grad: null
  clip_mode: 'norm'

lr:
  sched: 'cosine'
  lr: 1e-3
  noise: null
  noise_pct: 0.67
  noise_std: 1.0
  cycle_mul: 1.0
  cycle_decay: 0.5
  cycle_limit: 1
  k_decay: 1.0
  warmup_lr: 1e-6
  min_lr: 1e-6
  epochs: 100
  epoch_repeats: 0
  start_epoch: null
  decay_epochs: 50
  warmup_epochs: 5
  cooldown_epochs: 25
  patience_epochs: 10
  decay_rate: 0.1
  multistep_milestones: [25, 50, 75, 100]