use_wandb: True
use_sweep: False
verbose: False
train_embedding: True
pin_mem: True

seed: 2
gpus: 1
cpus: 1
workers: 16
device: 'cuda'

data_dir: '~/data'
dataset: 'prism_grid_dataset_224.hdf5'

checkpoint_path: './ckpt/'
check_val_every_n_epoch: 1

experiment: "koopman_Backbone_search_0"
project: "v1"
notes: "Staic field"

embedding:
  name: 'koopman'
  pretrained: False
  ckpt_path: "./ckpt/"
  image_dim: 32
  
  channels: 3
  backbone: "Conv"
  fc_dim: 256
  embedding_dim: 140
  backbone_dim: 128

autoregressive: 
  name: "GPT2" 
  pretrained: False
  ckpt_path: "./ckpt/" 

opt:
  name: 'adamw'
  eps: 1e-8
  momentum: 0.9
  beta0: 0.9
  beta1: 0.999
  weight_decay: 1e-8

learning:

  epochs: 300
  start_epoch: 0

  block_size_train: 8
  stride_train: 4
  batch_size_train: 128
  n_data_train: -1
  
  batch_size_val: 16
  block_size_val: 32
  stride_val: 32
  
  k_decay: 1.0
  
  lr: 1e-4
  min_lr: 1e-6
  warmup_lr: 1e-6
  gamma: 0.995

  sched: 'exponential'
  multistep_milestones: [25, 50, 75, 100]