use_wandb: False
use_sweep: False
verbose: False
pin_mem: True

seed: 2
gpus: 1
cpus: 1
workers: 16
device: 'cuda'

data_dir: '~/data'
viz_dir: '~/data/viz/'
dataset: 'prism_grid_dataset_224.hdf5'

experiment: "koopman_Backbone_search_0"
project: "v1"
notes: "Staic field"

embedding:
  sweep_id: 'no_id'
  display_name: 'no_name'
  name: 'koopman'
  pretrained: False
  ckpt_path: "./ckpt/"
  image_size: 32
  
  channels: 3
  backbone: "Conv"
 
  fc_dim: 32
  embedding_dim: 32
  backbone_dim: 32

  state_dims: [2, 64, 128]

autoregressive: 
  name: "GPT2" 
  pretrained: False
  ckpt_path: "./ckpt/model_name"
  embedding_model_ckpt_path: "C:\\Users\\s175407\\Desktop\\transformers4physics\\outputs\\2022-03-28\\22-57-28\\ckpt\\no_name.pth" 

  activation_function: "gelu_new"
  layer_norm_epsilon: 1e-5
  initializer_range: 0.01

  embedding_dim: 32
  n_ctx: 16
  n_layer: 6
  n_head: 4

  output_hidden_states: False
  output_attentions: False

opt:
  name: 'adamw'
  eps: 1e-8
  momentum: 0.9
  beta0: 0.9
  beta1: 0.999
  weight_decay: 1e-8

learning:

  epochs: 2
  start_epoch: 0

  block_size_train: 6
  stride_train: 6
  batch_size_train: 64
  n_data_train: 50
  
  batch_size_val: 16
  block_size_val: 32
  stride_val: 32
  
  lr: 1e-3
  min_lr: 1e-3
  warmup_lr: 1e-3
  gamma: 0.995
  k_decay: 1.0
  sched: 'exponential'